# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  db:
    image: mysql:8.0-bookworm
    container_name: smart40n1_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3307:3306 #Mapeamento da porta 3306 do container para a porta 3307 do host
    volumes:
      - db_data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql # Inicializa o schema

  app:
    build:
      context: .
    container_name: smart40n1_app
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  db_data: